version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
        environment:
          TZ: America/New_York
          PIPENV_VENV_IN_PROJECT: "TRUE"
          DATABASE_URL: postgres://postgres@localhost/data_ingest
          CI_TESTING: "TRUE"

      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: data_ingest

    steps:
      - checkout
      - restore_cache:
          key: v1-py-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Setup environment
          command: |
            pip install pipenv
            pipenv install --dev

      - save_cache:
          paths:
            - ./.venv
          key: v1-py-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Django Data Ingest test suite
          command: pipenv run coverage run runtests.py

      - run:
          name: Build Coverage report
          command: pipenv run coverage report

      - run:
          name: Flake8
          command: pipenv run flake8

      - run:
          name: Bandit
          command: pipenv run bandit -r .

      - run:
          name: Codecov
          command: pipenv run codecov
