# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='unique_metadata_fields',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.TextField(default='pending'),
        ),
    ]
